[package]
name = "triib-cli"
description = "Headless ATDECC controller"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[[bin]]
name = "triib-cli"
path = "src/main.rs"

[dependencies]
atdecc = { workspace = true, features = ["std"] }
avb-net = { workspace = true, features = ["std"] }
